version: 0.0
os: linux
files:
- source: /
  destination: /var/www/html/new
permissions:
- object: /var/www/html/new
  pattern: "**"
  owner: ubuntu
  group: ubuntu
  mode: 777
  type:
  - file
  - directory
hooks:
  BeforeInstall:
  - location: deployment/codedeploy-backup.sh
    runas: ubuntu
  ApplicationStart:
  - location: deployment/install-deps.sh
    runas: ubuntu
  ValidateService:
  - location: deployment/codedeploy-restart.sh
    runas: ubuntu
